export const ADD_CONVERSATION = "ADD_CONVERSATION";

export const REMOVE_CONVERSATION = "REMOVE_CONVERSATION";

export const ADD_MESSAGE = "ADD_MESSAGE";

export const LOAD_CONVERSATION = "LOAD_CONVERSATION";

export const CLOSE_CONVERSATION = "CLOSE_CONVERSATION";

export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
