export const USER_ONLINE = "USER_ONLINE";

export const OPEN_CONVERSATION = "OPEN_CONVERSATION";

export const LOAD_MESSAGE_GAME = "LOAD_MESSAGE_GAME";

export const ADD_MESSAGE_GAME = "ADD_MESSAGE_GAME";

export const ADD_PARTICIPANT_GAME = "ADD_PARTICIPANT_GAME";

export const CREATE_ROOM_GAME = "CREATE_ROOM_GAME";

export const LOADING_CREATE_ROOM_GAME = "LOADING_CREATE_ROOM_GAME";

export const LOAD_ROOMS_GAME = "LOAD_ROOMS_GAME";

export const LOADED_ROOMS_GAME = "LOADED_ROOMS_GAME";

export const LOADING_RANKINGS = "LOADING_RANKINGS";

export const GET_RANKINGS = "GET_RANKINGS";

export const TOPUP_LOGIN = "TOPUP_LOGIN";

export const CLOSE_TOPUP_MODAL = "CLOSE_TOPUP_MODAL";

export const OPEN_PASSWORD_MODAL = "OPEN_PASSWORD_MODAL";

export const CLOSE_PASSWORD_MODAL = "CLOSE_PASSWORD_MODAL";

export const LOAD_INFORMATION_ROOM = "LOAD_INFORMATION_ROOM";

export const LOADED_INFORMATION_ROOM = "LOADED_INFORMATION_ROOM";

export const GUEST_JOIN_ROOM = "GUEST_JOIN_ROOM";

export const GUEST_LEAVE_ROOM = "GUEST_LEAVE_ROOM";
