export const USER_ONLINE = "USER_ONLINE";

export const OPEN_CONVERSATION = "OPEN_CONVERSATION";

export const LOAD_MESSAGE_GAME = "LOAD_MESSAGE_GAME";

export const ADD_MESSAGE_GAME = "ADD_MESSAGE_GAME";

export const ADD_PARTICIPANT_GAME = "ADD_PARTICIPANT_GAME";

export const CREATE_ROOM_GAME = "CREATE_ROOM_GAME";

export const LOADING_CREATE_ROOM_GAME = "LOADING_CREATE_ROOM_GAME";

export const LOAD_ROOMS_GAME = "LOAD_ROOMS_GAME";

export const LOADED_ROOMS_GAME = "LOADED_ROOMS_GAME";

export const SAVE_PARTICIPANTS_ROOM_GAME = "SAVE_PARTICIPANTS_ROOM_GAME";
