export const USER_ONLINE = "USER_ONLINE";

export const OPEN_CONVERSATION = "OPEN_CONVERSATION";

export const LOAD_MESSAGE_GAME = "LOAD_MESSAGE_GAME";

export const ADD_MESSAGE_GAME = "ADD_MESSAGE_GAME";

export const ADD_PARTICIPANT_GAME = "ADD_PARTICIPANT_GAME";
