export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";

export const LOGIN_FACEBOOK_SUCCESS = "LOGIN_FACEBOOK_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_LOADING = "LOGIN_LOADING";

export const USER_LOADING = "USER_LOADING";

export const USER_LOADED = "USER_LOADED";

export const USER_RESEND_MAIL_SUCCESS = "USER_RESEND_MAIL_SUCCESS";

export const USER_RESEND_MAIL_FAIL = "USER_RESEND_MAIL_FAIL";

export const USER_RESEND_MAIL_LOADING = "USER_RESEND_MAIL_LOADING";

export const USER_VALIDATE_EMAIL_LOADING = "USER_VALIDATE_EMAIL_LOADING";

export const USER_VALIDATE_EMAIL_SUCCESS = "USER_VALIDATE_EMAIL_SUCCESS";

export const USER_VALIDATE_EMAIL_FAIL = "USER_VALIDATE_EMAIL_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";

export const REGISTER_LOADING = "LOGIN_LOADING";

export const AUTH_ERROR = "AUTH_ERROR";

export const GET_AUTH = "GET_AUTH";

export const USER_LOGOUT = "USER_LOGOUT";
